server:
  port: 8567
#  servlet:
#    context-path: /sell
spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  application:
     name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
swagger:
    docket:
      base-package: io.github.jackson
    enabled: true
